# Generated by Django 5.1 on 2024-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.IntegerField(unique=True),
        ),
    ]
